#!/usr/bin/env bash

AWS_REGION=us-east-1
CFN_TEMPLATE=file:///$PWD/vpc-multi-tier-template.yml

FILES=( \
#  "VPC-Platform" \
  "VPC-Security" \
#  "VPC-Audit" \
#  "VPC-Sandbox" \ 
#  "VPC-NonProd" \ 
#  "VPC-PreProd" \ 
#  "VPC-Prod"
)

for STACK_NAME in "${FILES[@]}"
do
   : 
   STACK_NAME_LOWER=$(echo "$STACK_NAME" | awk '{print tolower($0)}')
   aws cloudformation create-stack \
                     --stack-name ${STACK_NAME} \
                     --template-body ${CFN_TEMPLATE} \
                     --parameters file:///$PWD/vpc-data/${STACK_NAME_LOWER}-account-us-east-1-parameters.json \
                     --capabilities CAPABILITY_NAMED_IAM \
                     --region ${AWS_REGION}
done
