#!/usr/bin/env bash

AWS_REGION=us-east-1
STACK_NAME=TestAdminGroupUser

aws cloudformation create-stack \
                     --stack-name ${STACK_NAME} \
                     --template-body file:///$PWD/../admin-group-user.yml \
                     --parameters file:///$PWD/parameters.json \
                     --capabilities CAPABILITY_NAMED_IAM \
                     --region ${AWS_REGION}

aws cloudformation wait stack-create-complete --stack-name ${STACK_NAME} --region ${AWS_REGION}

cat validate.rb | inspec shell -t aws://${AWS_REGION}
