#!/usr/bin/env bash

AWS_REGION=us-east-1
STACK_NAME=Test-VPC

aws cloudformation delete-stack \
                     --stack-name ${STACK_NAME} \
                     --region ${AWS_REGION}

aws cloudformation wait stack-delete-complete --stack-name ${STACK_NAME} --region ${AWS_REGION}
